### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by PerhapsSomeone** [PerhapsSomeone/simple-social-network#1]
If you happen to find security issues, please leave them here.

**Comment by Christian1998** [comment]
Schau dir mal PDO und OOP an, bevor du weiter lernst :) Hilft ungemein, wenn man es nicht anders also ohne OOP (Objekt Orientierte Programmierung).
PS: 

poll.php?action=view&id

poll-action bekommst du per $_GET ['action'] heraus, genauso die ID :)

LG von einem Devrant'ler

**Comment by PerhapsSomeone** [comment]
Danke dir.
